name: Unit tests

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt
      - name: Run tests
        run: |
          export PYTHONPATH="$PYTHONPATH:$PWD/src" && coverage run && coverage report -m
      - name: Publish code coverage to codeclimate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ vars.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
          debug: true
      - name: Publish code coverage to qlty.sh
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ vars.QLTY_COVERAGE_TOKEN }}
          files: coverage.xml
